In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os

# Chemin d'accès au dossier contenant les images
path = "/content/drive/MyDrive/data_trié"

# Compter le nombre d'images
count = 0
for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".jpg") or (".png"):
            count += 1

# Afficher le résultat
print(f"Le dossier '{path}' contient {count} images.")


Le dossier '/content/drive/MyDrive/data_trié' contient 19367 images.


In [ ]:
"""
import os
import shutil

# Chemin du dossier principal contenant les sous-dossiers
path= "/content/drive/MyDrive/faces_data"
path1="/content/drive/MyDrive/data_trié"

# Dictionnaire pour stocker les images classées par ID
id_dict = {}

# Parcourir chaque sous-dossier
for subdir in os.listdir(path):
    # Chemin complet du sous-dossier
    subdir_path = os.path.join(path, subdir)
    # Vérifier si le sous-dossier est un dossier
    if os.path.isdir(subdir_path):
        # Parcourir chaque fichier dans le sous-dossier
        for filename in os.listdir(subdir_path):
            # Vérifier si le fichier est une image
            if filename.endswith(".jpg") or filename.endswith(".png"):
                # Extraire l'ID à partir du nom du fichier
                id = filename.split(".")[1]
                # Ajouter l'image au dictionnaire correspondant à son ID
                if id in id_dict:
                    id_dict[id].append(os.path.join(subdir_path, filename))
                else:
                    id_dict[id] = [os.path.join(subdir_path, filename)]

# Créer un nouveau dossier pour chaque ID et y copier les images correspondantes
for id in id_dict:
    # Chemin du nouveau dossier pour cet ID
    new_dir_path = os.path.join(path1, "ID_" + id)
    # Créer le nouveau dossier s'il n'existe pas déjà
    if not os.path.exists(new_dir_path):
        os.makedirs(new_dir_path)
    # Copier chaque fichier d'image correspondant à cet ID dans le nouveau dossier
    for image_path in id_dict[id]:
        shutil.copy(image_path, new_dir_path)
"""

In [ ]:
"""
import os
import random
from shutil import copyfile

# Chemin vers le dossier contenant les 82 sous-dossiers représentant chaque classe
data_dir = '/content/drive/MyDrive/data_trié'

# Chemin vers le dossier où vous voulez stocker les images de train et de test
train_dir = '/content/drive/MyDrive/train_data'
test_dir = '/content/drive/MyDrive/test_data'

# Pourcentage de données d'entraînement
train_percentage = 0.8

# Parcourez chaque dossier représentant chaque classe
for class_dir in os.listdir(data_dir):
    class_path = os.path.join(data_dir, class_dir)
    if not os.path.isdir(class_path):
        continue

    # Créer des dossiers de train et de test pour chaque classe
    train_class_path = os.path.join(train_dir, class_dir)
    test_class_path = os.path.join(test_dir, class_dir)
    os.makedirs(train_class_path, exist_ok=True)
    os.makedirs(test_class_path, exist_ok=True)

    # Parcourez chaque fichier dans le dossier de la classe
    files = os.listdir(class_path)
    random.shuffle(files)
    train_size = int(len(files) * train_percentage)

    for i, file_name in enumerate(files):
        # Déterminer si l'image doit être placée dans le dossier de train ou de test
        if i < train_size or (i == train_size and len(files) % 2 == 1):
            dest_dir = train_class_path
        else:
            dest_dir = test_class_path

        # Copier l'image dans le dossier de destination
        src_path = os.path.join(class_path, file_name)
        dest_path = os.path.join(dest_dir, file_name)
        copyfile(src_path, dest_path)
"""

In [ ]:
import os

# Chemin d'accès au dossier contenant les images
path = "/content/drive/MyDrive/train_data"

# Compter le nombre d'images
count = 0
for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith(".jpg") or (".png"):
            count += 1

# Afficher le résultat
print(f"Le dossier '{path}' contient {count} images.")


Le dossier '/content/drive/MyDrive/train_data' contient 15651 images.


In [ ]:
import os
import numpy as np
from PIL import Image

# chemin du dossier contenant les images
folder_path = '/content/drive/MyDrive/Expériementation_Adience_DB/test_data'

# Liste des noms de tous les sous-dossiers
subfolders = [f.path for f in os.scandir(folder_path) if f.is_dir()]

# Créer une liste vide pour stocker les tableaux d'images
X_train = []
# Créer une liste vide pour stocker les étiquettes
X_labels = []

# Parcourir chaque sous-dossier
for i, subfolder in enumerate(subfolders):
    # Liste des fichiers dans le sous-dossier
    file_names = [f.path for f in os.scandir(subfolder) if f.is_file()]
    # Parcourir chaque fichier
    for file_name in file_names:
        # Ouvrir l'image avec PIL
        image = Image.open(file_name)
        image = image.convert('RGB')
        # Redimensionner l'image à (299, 299)
        image = image.resize((160, 160))
        # Convertir l'image en tableau numpy
        image_array = np.array(image)
        # Ajouter le tableau d'image à la liste
        X_train.append(image_array)
        # Ajouter l'étiquette à la liste
        X_labels.append(i)

X_train = np.array(X_train)


In [ ]:
max(X_labels)

2282

In [ ]:
print(len(X_train))
print(len(X_labels))

15651
15651


In [ ]:


import os
import numpy as np
from PIL import Image

# chemin du dossier contenant les images
folder_path = '/content/drive/MyDrive/Expériementation_Adience_DB/test_data'

# Liste des noms de tous les sous-dossiers
subfolders = [f.path for f in os.scandir(folder_path) if f.is_dir()]

# Créer une liste vide pour stocker les tableaux d'images
Y_test = []
# Créer une liste vide pour stocker les étiquettes
Y_labels= []

# Parcourir chaque sous-dossier
for i, subfolder in enumerate(subfolders):
    # Liste des fichiers dans le sous-dossier
    file_names = [f.path for f in os.scandir(subfolder) if f.is_file()]
    # Parcourir chaque fichier
    for file_name in file_names:
        # Ouvrir l'image avec PIL
        image = Image.open(file_name)
        image = image.convert('RGB')
        # Redimensionner l'image à (299, 299)
        image = image.resize((160, 160))
        # Convertir l'image en tableau numpy
        image_array = np.array(image)
        # Ajouter le tableau d'image à la liste
        Y_test.append(image_array)
        # Ajouter l'étiquette à la liste
        Y_labels.append(i)


Y_test = np.array(Y_test)


In [ ]:
print(len(Y_labels))
print(len(Y_test))

3716
3716


In [ ]:
!pip install pillow


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import cv2
import matplotlib.pyplot as plt


In [ ]:
pip install keras-facenet


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 22.8 MB/s eta 0:00:00
  Created wheel for keras-facenet: filename=keras_facenet-0.3.2-py3-none-any.whl size=10385 sha256=310075f86d80e94fb8a8691b3b19a81f0d4ec8b3f29502527a4715aabb2f433c
  Stored in directory: /root/.cache/pip/wheels/1d/d8/a9/85cf04ea29321d2afcb82c0caaafdca9195385f9d68cbc7185
Successfully built keras-facenet


In [ ]:
from keras_facenet import FaceNet
MyFaceNet = FaceNet()


In [ ]:
def get_embedding(model, face):
    # scale pixel values
    # standardization
    # transfer face into one sample (3 dimension to 4 dimension)
    sample = np.expand_dims(face, axis=0)
    # make prediction to get embedding
    yhat = MyFaceNet.embeddings(sample)
    return yhat[0]
    


In [ ]:
# convert each face in the train set into embedding
emdTrainX = list()
for face in X_train:
    emd = get_embedding(MyFaceNet,face)
    emdTrainX.append(emd)
    
emdTrainX = np.asarray(emdTrainX)
print(emdTrainX.shape)



Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
1/1 [==============================] - 0s 170ms/step
(15651, 512)


In [ ]:
# convert each face in the test set into embedding
emdTestX = list()
for face in Y_test:
    emd = get_embedding(MyFaceNet, face)
    emdTestX.append(emd)
emdTestX = np.asarray(emdTestX)
print(emdTestX.shape)

1/1 [==============================] - 0s 104ms/step
(3716, 512)


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import Normalizer
from sklearn.svm import SVC

print("Dataset: train=%d, test=%d" % (emdTrainX.shape[0], emdTestX.shape[0]))
# normalize input vectors
in_encoder = Normalizer()
emdTrainX_norm = in_encoder.transform(emdTrainX)
emdTestX_norm = in_encoder.transform(emdTestX)



Dataset: train=15651, test=3716


In [ ]:
# label encode targets
out_encoder = LabelEncoder()
out_encoder.fit(X_labels)
trainy_enc = out_encoder.transform(X_labels)
testy_enc = out_encoder.transform(Y_labels)

In [ ]:
# fit model
model = SVC(kernel='rbf',probability=True,C=100)
SVM=model.fit(emdTrainX_norm, trainy_enc)
# predict
yhat_train = model.predict(emdTrainX_norm)
yhat_test = model.predict(emdTestX_norm)
# score
score_train = accuracy_score(trainy_enc, yhat_train)
score_test = accuracy_score(testy_enc, yhat_test)
# summarize
print('Accuracy: train=%.3f, test=%.3f' % (score_train*100, score_test*100))


Accuracy: train=99.987, test=93.272


In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import ConfusionMatrixDisplay
res = confusion_matrix(testy_enc, yhat_test)
for i in range(0,len(res)):
  print(res[i])
print("Confusion Matrix")
print(res)
print(f"Test Set: {len(Y_test)}")
print(f"Accuracy = {score_test*100} %")
print(classification_report(testy_enc, yhat_test))

[1 0 0 ... 0 0 0]
[0 1 0 ... 0 0 0]
[0 0 1 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ... 0 0 0]
[0 0 0 ...

/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.